//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Regiao
    {
        public long IdRegiao { get; set; }

        public string Descricao { get; set; }
        public byte Ativo { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Estado EstadoRegiao { get; set; }
    }
}
